type QrCodeProps = {
  /** The URL or text encoded into the QR code. */
  data: string;
  /** Rendered size of the QR image, in pixels. */
  size?: number;
  className?: string;
};

/**
 * Lightweight QR code rendered from a generator service — no extra
 * dependencies. Encodes `data` (e.g. the Google Play URL) so users can
 * scan it from another device.
 */
export default function QrCode({ data, size = 160, className = "" }: QrCodeProps) {
  const src = `https://api.qrserver.com/v1/create-qr-code/?size=${size}x${size}&margin=0&data=${encodeURIComponent(
    data,
  )}`;

  return (
    // Plain <img> on purpose: the QR is generated by an external service,
    // so next/image optimization (and its domain allow-list) is unnecessary.
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={src}
      alt="QR code to download Atom on Google Play"
      width={size}
      height={size}
      className={className}
      loading="lazy"
    />
  );
}
